/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package uecontextmanagement

import (
	"github.com/nycu-ucr/gonet/http"

	"github.com/nycu-ucr/gin"
)

// DeregistrationSmsf3gppAccess - delete the SMSF registration for 3GPP access
func HTTPDeregistrationSmsf3gppAccess(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
